### ISSUE TITLE
Use the hash of a file as its filename instead of user-supplied filename

### ISSUE THREAD

**Issue by ezist** [typicalname0/4grounds#9]
This will prevent potential XSS and remove chances of filename collision.

**Comment by bloxxite** [comment]
yes i am doing that in my fork

**Comment by KScottDB** [comment]
i was thinking of doing this myself. i think this is pretty important.

**Comment by ezist** [comment]
Partially fixed in c091225; user pfps and songs will be set to the ID of the user setting them.

**Comment by typicalname0** [comment]
thanks @ezist, it's fixed and live on the site.
